
GAME_MODE_TUBIAN = "tubian"
GAME_MODE_TUCHENG = "tucheng"

PLAYER_STATUS_INGAME = "inGame"
PLAYER_STATUS_OFFLINE = "offline"
PLAYER_STATUS_WAITING = "waiting"

ROLE_SEER = "seer"
ROLE_WEREWOLF = "werewolf"
ROLE_ALPHAWOLF = "alphaWolf"
ROLE_VILLAGER = "villager"
ROLE_GUARD = "guard"
ROLE_VILLAGEHEAD = "villageHead"
ROLE_WITCH = "witch"
ROLE_ARMSDEALER= "armsDealer"

PROCESS_DETECTIVE_NOMINATION = "detectiveNomination"
PROCESS_DETECTIVE_VOTING = "detectiveVoting"
PROCESS_DETECTIVE_OVER = "detectiveOver"
PROCESS_MORNING = "morning"
PROCESS_VOTING = "voting"


PROCESS = [PROCESS_MORNING]
